server:
  address: 127.0.0.1
  port: 8080

spring:
  liquibase:
    change-log: classpath:liquibase/master.xml
    enabled: false
  jpa:
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: none
