spring:
  jpa:
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: liquibase/master.xml
    enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs

server:
  address: 127.0.0.1
  port: 8080
  servlet:
    context-path: /

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true
