spring:
  datasource:
    url: jdbc:h2:mem:database
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

          