server:
  address: 127.0.0.1
  port: 9000
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/database?createDatabaseIfNotExist=true&useSSL=true
    username: root
    password: root-password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

logging:
  level:
    org.springframework.security: debug
